Updated TODOs
All TODOs have been completed.  However, the PhoneFormatter ended up
just removing all the phone numbers instead of formatting them.

Also, every time I submit a Login, I am not getting an Action Script
error:

Error: The source attribute must be specified when the property
attribute is specified.
	at
mx.validators::Validator/getValueFromSource()[/Users/aharui/release4.13.
0/